# Generated by Django 5.1.1 on 2025-02-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('image6', models.ImageField(upload_to='')),
                ('image7', models.ImageField(upload_to='')),
                ('image8', models.ImageField(upload_to='')),
                ('image9', models.ImageField(upload_to='')),
                ('image10', models.ImageField(upload_to='')),
                ('image11', models.ImageField(upload_to='')),
                ('image12', models.ImageField(upload_to='')),
                ('image13', models.ImageField(upload_to='')),
                ('image14', models.ImageField(upload_to='')),
                ('image15', models.ImageField(upload_to='')),
                ('image16', models.ImageField(upload_to='')),
                ('image17', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('image6', models.ImageField(upload_to='')),
                ('image7', models.ImageField(upload_to='')),
                ('image8', models.ImageField(upload_to='')),
                ('image9', models.ImageField(upload_to='')),
                ('image10', models.ImageField(upload_to='')),
                ('image11', models.ImageField(upload_to='')),
                ('image12', models.ImageField(upload_to='')),
                ('image13', models.ImageField(upload_to='')),
                ('image14', models.ImageField(upload_to='')),
            ],
        ),
    ]
