# Generated by Django 5.1.1 on 2025-02-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpage1',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='studentpage1',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='studentpage1',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='studentpage1',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='studentpage1',
            name='image16',
        ),
        migrations.RemoveField(
            model_name='studentpage1',
            name='image17',
        ),
        migrations.RemoveField(
            model_name='teacherpage1',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='teacherpage1',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='teacherpage1',
            name='image14',
        ),
    ]
