# Generated by Django 5.1.1 on 2025-02-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_customuser_username_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
