# Generated by Django 5.1.1 on 2025-02-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
