# Generated by Django 5.1.1 on 2025-02-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_profile_username_profile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
