# Generated by Django 5.1.1 on 2025-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_profileuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='role',
            field=models.CharField(choices=[('teacher', "O'qituvchi"), ('student', 'Talaba')], max_length=10),
        ),
    ]
