# Generated by Django 5.1.1 on 2025-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_profileuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
