# Generated by Django 5.1.1 on 2025-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_profileuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='role',
            field=models.CharField(choices=[('teacher', "O'qituvchi"), ('student', 'Talaba')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
