# Generated by Django 5.1.1 on 2025-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_profileuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', "O'qituvchi"), ('student', 'Talaba')], default='student', max_length=10, null=True),
        ),
    ]
