# Generated by Django 5.1.1 on 2025-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_profileuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
