# Generated by Django 5.1.1 on 2025-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_question_test_remove_usertestresult_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='a_javob',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='b_javob',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='c_javob',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='d_javob',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
