# Generated by Django 5.1.1 on 2025-02-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_question_a_javob_alter_question_b_javob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
