# Generated by Django 5.1.1 on 2025-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_profileuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
