# Generated by Django 5.1.1 on 2025-02-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_profileuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('a_javob', models.CharField(max_length=200)),
                ('b_javob', models.CharField(max_length=200)),
                ('c_javob', models.CharField(max_length=200)),
                ('d_javob', models.CharField(max_length=200)),
                ('javob', models.CharField(max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lecture1')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='laboratory1',
            name='laboratiya_video',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practic1',
            name='practic_video',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
