# Generated by Django 5.1.1 on 2025-02-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_lecturetest_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('a_javob', models.CharField(max_length=200)),
                ('b_javob', models.CharField(max_length=200)),
                ('c_javob', models.CharField(max_length=200)),
                ('d_javob', models.CharField(max_length=200)),
                ('javob', models.CharField(max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.laboratory1')),
            ],
        ),
        migrations.CreateModel(
            name='PracticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('a_javob', models.CharField(max_length=200)),
                ('b_javob', models.CharField(max_length=200)),
                ('c_javob', models.CharField(max_length=200)),
                ('d_javob', models.CharField(max_length=200)),
                ('javob', models.CharField(max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.practic1')),
            ],
        ),
    ]
