# Generated by Django 5.1.1 on 2025-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_laboratorytest_practictest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
