# Generated by Django 5.1.1 on 2025-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_useractivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='time_spent',
        ),
    ]
