# Generated by Django 5.1.1 on 2025-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_useractivity_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
