# Generated by Django 5.1.1 on 2025-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_useractivity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
