# Generated by Django 5.1.1 on 2025-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_userprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture1',
            name='maruza_raqam',
            field=models.IntegerField(max_length=5),
        ),
    ]
