# Generated by Django 5.1.1 on 2025-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_lecture1_maruza_raqam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practic1',
            name='practic_raqam',
            field=models.IntegerField(),
        ),
    ]
