# Generated by Django 5.1.1 on 2025-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_rename_userprogress_userlaboratoryprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory1',
            name='laboratoriya_raqam',
            field=models.IntegerField(),
        ),
    ]
