# Generated by Django 5.1.1 on 2025-03-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_laboratory1_laboratoriya_raqam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory1',
            old_name='laboratoriya_matni',
            new_name='laboratory_matni',
        ),
        migrations.RenameField(
            model_name='laboratory1',
            old_name='laboratoriya_nomi',
            new_name='laboratory_nomi',
        ),
        migrations.RenameField(
            model_name='laboratory1',
            old_name='laboratoriya_raqam',
            new_name='laboratory_raqam',
        ),
        migrations.RenameField(
            model_name='laboratory1',
            old_name='laboratiya_video',
            new_name='laboratory_video',
        ),
    ]
