# Generated by Django 5.1.1 on 2025-03-06 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
