# Generated by Django 5.1.1 on 2025-03-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_admincontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminContact',
            new_name='Admin_Contact',
        ),
    ]
