# Generated by Django 5.1.1 on 2025-03-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='meet_link',
        ),
    ]
