# Generated by Django 5.1.1 on 2025-03-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_remove_lesson_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meet_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
