# Generated by Django 5.1.1 on 2025-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_lesson_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_contact',
            name='extra_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
