# Generated by Django 5.1.1 on 2025-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_admin_contact_extra_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture1',
            name='maruza_matni',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
