# Generated by Django 5.1.1 on 2025-04-06 10:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_lecture1_maruza_matni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture1',
            name='maruza_matni',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
