# Generated by Django 5.1.1 on 2025-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_lecture1_maruza_matni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture1',
            name='maruza_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
