# Generated by Django 5.1.1 on 2025-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_lecture1_maruza_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
