# Generated by Django 5.1.1 on 2025-04-06 16:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_about_us_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us_model',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
