# Generated by Django 5.1.1 on 2025-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_examtest_userexamattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtest',
            name='d_option',
        ),
        migrations.AlterField(
            model_name='examtest',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1),
        ),
    ]
