# Generated by Django 5.1.1 on 2025-04-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_examtest_teacher_examtest_test_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamTest',
        ),
    ]
