from django.urls import path
from .views import *

urlpatterns = [
    path('register/', RegisterAPIView.as_view(), name='api-register'),
    path('login/', LoginAPIView.as_view(), name='api-login'),
    path('role-select/', RoleSelectAPIView.as_view(), name='api-role-select'),
    path('teacher-profile/', TeacherProfileUpdateAPIView.as_view(), name='api-teacher-profile'),
    path('student-profile/', StudentProfileUpdateAPIView.as_view(), name='api-student-profile'),
    path('request-reset/', RequestPasswordResetAPI.as_view()),
    path('verify-code/', VerifyCodeAPI.as_view()),
    path('reset-password/', ResetPasswordAPI.as_view()),
    path('teacher-profile-fix/', TeacherProfileUpdateAPI.as_view(), name='teacher-profile-update'),
    path('student-profile-fix/', StudentProfileUpdateAPI.as_view(), name='student-profile-update'),
    path('lecture/<int:lesson_id>/questions/', get_lecture_test),
    path('lecture/<int:lesson_id>/submit/', submit_lecture_test),
    path('practic/<int:lesson_id>/questions/', get_practic_test),
    path('practic/<int:lesson_id>/submit/', submit_practic_test),
    path('laboratory/<int:lesson_id>/questions/', get_laboratory_test),
    path('laboratory/<int:lesson_id>/submit/', submit_laboratory_test),
    path('teacherpage/', get_teacher_images),
    path('studentpage/', get_student_images),
    path('profile/', get_profile_images),
    path('objects/',get_objects_images),
    path('lectures/', lecture_list),            
    path('lectures/<int:pk>/', lecture_detail),
    path('practic/', practic_list),            
    path('practic/<int:pk>/', practic_detail),
    path('laboratory/', laboratory_list),            
    path('laboratory/<int:pk>/', laboratory_detail),
    path('selfstudy/',get_selfstudy),
    path('trio/',get_trio_images),
    path('bilim/',get_bilim_images),
    path('triostudent/',get_triostudent_images),
    path('activity/weekly/', weekly_activity_api),
    path('activity/log/', log_activity_api),
    path("weekly-user/", weekly_user_count_api, name="weekly_user_count_api"),
    path('stars/', get_user_stars),
    path('stars-daily/', get_daily_stars),
    path('admin-contact/', get_admin_contact),
    path('media/', get_media_images),
    path('about-us/', get_about_us),
    path('send-message/', send_message_api, name='send_message_api'),
    path('get-students/', get_students_api, name='get_students_api'),
    path('get-notifications/', get_notifications_api, name='get_notifications_api'),
    path('mark-notification-as-read/', mark_notification_as_read_api, name='mark_notification_as_read_api'),
    path('get-unread-notifications/', get_unread_notifications_api, name='get_unread_notifications_api'),
    path('get-teachers/', get_teachers_api, name='get_teachers_api'),
    path('create-lesson/', create_lesson),
    path('get-lesson/', get_lessons),
    path('end-stream/', end_stream),
    path('exams/', get_exam_list, name='api_get_exam_list'),
    path('exams/<int:exam_id>/start/', start_exam, name='api_start_exam'),
    path('exams/<int:exam_id>/submit/', submit_exam, name='api_submit_exam'),
    path('exams/<int:exam_id>/delete/', delete_exam, name='api_delete_exam'),
]
